---
title: "Summary of Criticals Minerals Mapping Initiative"
subtitle: "Using data compiled by Geoscience Australia, the Geological Survey of Canada and the United States Geological Survey" 
author: "Yuri Gomes"
date: "`r Sys.Date()`"
format:
  html:
    theme:
      light: cosmo
      dark: cosmo
    code-tools: true
    self-contained: true
editor: visual
---

## Introduction

This report brings a summary of the South America's deposits of Copper (Cu), Iron (Fe) and Lithium (Li) contained in the Critical Minerals Mapping Initiative (CMMI) database, a collection of geochemical analysis of 7,000 samples from mineral deposits in 60 countries.

This report is for education and science communication only. You are free to share, copy and redistribute the material in any medium or format. You may not use the material for commercial purposes.

The full dataset as well as its information, authors and metadata can be accessed [here](https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/145496).

## Data Import

Geoscience Australia, the Geological Survey of Canada, and the US Geological Survey compiled CMMI from publicly available sources, including mineral deposit, geochemistry, and the OSNACA databases.

The dataset is divided into

``` {r}
library(tidyverse)
library(ggplot2)
library(leaflet)
library(here)

cmmi_dataset <-
  readr::read_csv(
    here::here("projeto_report_geoquimica/CriticalMineralDepositsGeochemistry.csv"))

```



